[theme]

# Primary accent for interactive elements
primaryColor = '#c89b3c'

# Background color for the main content area
backgroundColor = '#0e1117'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#262730'

# Color used for almost all text
textColor = '#FAFAFA'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"